        TRANSPORT_FOOT = 0
        TRANSPORT_HORSE = 1
        TRANSPORT_CART = 2
        TRANSPORT_RAFT = 3
        TRANSPORT_FRIGATE = 4
        TRANSPORT_AIRCAR = 5
        TRANSPORT_SHUTTLE = 6
        TRANSPORT_PHANTOM = 7
        TRANSPORT_STAR_CRUISER = 8
        TRANSPORT_BATTLE_BASE = 9
        TRANSPORT_TIME_MACHINE = 10

        TILE_WATER = $00
        TILE_PLAYER = $08
